### ISSUE TITLE
Issues with Subpath in Registry name

### ISSUE THREAD

**Issue by noelmiller** [ublue-os/isogenerator#12]
Received a discord message about this in the ISO Thread.

Here is the example docker command: 
```
$ docker run --rm --privileged -v ./output:/isogenerator/output -e IMAGE_REPO="ghcr.io/ii" -e IMAGE_NAME="corehost/corehost" -e VARIANT="coreos" -e IMAGE_TAG="stable" ghcr.io/ublue-os/isogenerator
```

Relevant error: 
```
sed 's/@IMAGE_NAME@/corehost/corehost/'                        /isogenerator/lorax_templates/set_installer.tmpl.in > /isogenerator/lorax_templates/set_installer.tmpl
sed: -e expression #1, char 25: unknown option to `s'
make: *** [Makefile:50: lorax_templates/set_installer.tmpl] Error 1
```

We need to investigate this. Maybe it requires more escaping for sed to work properly?

**Comment by JasonN3** [comment]
What's the goal? If they are looking to push the image to `ghcr.io/ii/corehost/corehost`, they should be setting the repo to `ghcr.io/ii/corehost`. `IMAGE_NAME` is not meant to have a slash in it.

**Comment by noelmiller** [comment]
> What's the goal? If they are looking to push the image to `ghcr.io/ii/corehost/corehost`, they should be setting the repo to `ghcr.io/ii/corehost`. `IMAGE_NAME` is not meant to have a slash in it.

That makes sense to me. I will ask them to give that a try!

**Comment by BobyMCbobs** [comment]
> What's the goal? If they are looking to push the image to `ghcr.io/ii/corehost/corehost`, they should be setting the repo to `ghcr.io/ii/corehost`. `IMAGE_NAME` is not meant to have a slash in it.

It was being pushed to `ghcr.io/ii/corehost/corehost` since pulling across the [ucore reusable workflow](https://github.com/ublue-os/ucore/blob/main/.github/workflows/reusable-build.yml), which didn't work for this purpose (no need to build zfs, nvidia, etc...) so I copied out the workflow from the reusable into [this workflow](https://github.com/ii/corehost/blob/9e9eeb502b99ff13ed13e22495f02f8d3c677318/.github/workflows/build.yml) and that's where it was pushing to. Though just yesterday I managed to get it to just push to `ghcr.io/ii/corehost` (in [this change](https://github.com/ii/corehost/commit/974ff130afde3ef7cc6498f39b8d13553d0d6b85)).
